### ISSUE TITLE
After rejecting swap transaction using swapr value is locked when cow is selected

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#1342]
**Description**
After rejecting swap transaction using swapr value is locked when cow is selected

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Connect to gnosis
2. Select XDai as from and USDC as to in swapbox
3. Type 1 as value from
4. Select Swapr exchange
5. Click on Swap button and reject transaction
6. Select Cow exchange
7. Try to change from value

**Recording**

https://images.zenhubusercontent.com/209400598/cb0e7c03-8670-400e-b621-b3ede6711052/s.mp4

**Comment by jorgedclopes** [comment]
To add some developer insight. What is happening is that the approval state is changing `onClick` regardless of whether we approve or reject the transaction.
There is an uncaught exception in the swapCallback `execution` method. We can use this to "outcome" to decide the state of approval instead of the click.
