### ISSUE TITLE
<-- Back to Pair does not work in rewards program detail view if accessed via a shared link

### ISSUE THREAD

**Issue by pimato** [levelkdev/swapr-dapp#279]
So I just wanted to check out our farming test and used the link shared in keybase:

https://gateway.ipfs.io/ipfs/QmXsw1H6yiPpFGPUV2Ywe167uPZn7mZ8LsxwqwZWacHqAa/#/pools/0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1/0xb90D6bec20993Be5d72A5ab353343f7a0281f158/0x98236e9FaCCCa1740f22a46187b3E062F88d3720

<img width="669" alt="Bildschirmfoto 2021-06-15 um 09 57 45" src="https://user-images.githubusercontent.com/5337809/122015173-269a6680-cdc0-11eb-8673-65d66614879d.png">

The `<-- Back to Pair` Button does not work for me, but it should go back to the Pairs overview.

**Comment by MilanVojnovic95** [comment]
@0xVenky 
Tested this issue and the bug is still present but now that button is called 'back to rewards' and in the video below you can see how it is right now

https://user-images.githubusercontent.com/57331244/171337907-95b22ef2-b58f-4a66-ac2d-a68ffa3e073b.mp4

and how it is  if accessed via a shared link

https://user-images.githubusercontent.com/57331244/171338276-d502b48a-5f86-4130-8bb4-42cc6047f90b.mov

**Comment by MilanVojnovic95** [comment]
Retested on *develop* branch and the bug is no longer present
