### ISSUE TITLE
Gas estimate for Ethereum Mainnet

### ISSUE THREAD

**Issue by Mi-Lan** [levelkdev/swapr-dapp#595]
- Gas indicator next to SWAPR balance
![Screenshot 2022-01-28 at 14 40 05](https://user-images.githubusercontent.com/33226956/151556641-f3fc2509-a962-409b-9844-0acf187858b8.png)
- figma https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=6667%3A32165

**Comment by Mi-Lan** [comment]
@zamli Will clicking on this gas indicator do something?

**Comment by zamli** [comment]
> @zamli Will clicking on this gas indicator do something?

Here i have the two states for the gas indicator.
When clicked a small indicator pops up below it, this is only hidden if clicked on the same gas indicator again.

https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=6692%3A34417

**Comment by kingalg** [comment]
1. On chrome it's working with this extension https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf as mentioned by @Mi-Lan I confirm that without it I couldn't see the feature but after adding an add-on and reloading the page the feature is visible.
2. Is this suppose to work on responsive website? Feature disappear once the window goes into tablet mode. It doesn't move on the bottom of the page with SWPR and ETH info.
![Screenshot 2022-02-16 at 12 49 33](https://user-images.githubusercontent.com/68909168/154258836-174aaaf0-0363-4259-9bfe-ad30cc62264c.png)

![Screenshot 2022-02-16 at 12 49 51](https://user-images.githubusercontent.com/68909168/154258898-9aa66924-f086-4062-9171-7cb515b406a0.png)

**Comment by MilanVojnovic95** [comment]
The gas indicator is not visible on the Ethereum network.
It is visible on Arbitrum but there is no option to click so a small indicators ( fast, normal, slow ) pops up below it.
On Gnosis Chain it works normally and reacts to a click and in that case a small indicator appears.

There are also differences with the design from Figma and the implemented design
Gas indicator arrow is white and by design the numbers should not be larger than the 'Gas' icon in the indicator
![image](https://user-images.githubusercontent.com/57331244/157465755-55547317-17fc-475a-8acb-d1957fea4e98.png)
According to the design from Figma, it should be the same color as the other elements from the gas indicator
![image](https://user-images.githubusercontent.com/57331244/157466129-aaaa7177-44a6-446e-8ee2-82753c927bc7.png)
It can also be noticed that (fast, normal, slow) elements are not nicely centered within the indicator frame
![image](https://user-images.githubusercontent.com/57331244/157466400-ba81297a-5a2f-49dc-b6fd-3fe0fa69ba4a.png)
This is how it should be according to the Figma
![image](https://user-images.githubusercontent.com/57331244/157466509-e5a88f26-4fc8-47c6-9f80-c33c5823bd64.png)

I’m also not sure if this indicator should be present for Testnet as well?
Because it's not right now.

It also looks good on mobile devices and in tablet mode.
The only place where I noticed that there is a lack of responsiveness is on:
![image](https://user-images.githubusercontent.com/57331244/157468846-8d643ecc-6b4e-4dfe-9588-6933f6c1f837.png)

**Comment by 0xVenky** [comment]
> The gas indicator is not visible on the Ethereum network.

https://github.com/levelkdev/dxswap-dapp/pull/613#issue-1123437188



> It is visible on Arbitrum but there is no option to click so a small indicators ( fast, normal, slow ) pops up below it.

I think this is not available in Arbitrum. 

Agree on the fixes that are needed for the arrow color being white and to add a bit of padding to the FAST, NORMAL and SLOW pills.

Lets not worry about Galaxy Fold for now. :)
