### ISSUE TITLE
Swap and Send

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#644]
We would like to have this implemented exactly like how SUshi has implemented it.
![image](https://user-images.githubusercontent.com/55109759/155965140-d3203f43-d4e1-4afa-a57e-140ef69454c2.png)

When user has Expert mode turned ON, there should be an "Add Recipient" button appearing at the top of Swap button.

User clicks on Ad Recipient, there should be a new text field to enter an address or ENS name. The Swap field should be enabled only if the address is entered.
User enters the address (Swap button should be enabled) and then clicks on Swap button, we should place an action to Swap and then send the resulting Token1 to the address entered in the textbox.

Would be good to have a validation that the entered address is a valid ethereum adderss or not.

**Comment by MilanVojnovic95** [comment]
@0xVenky 
We have this implemented but in a slightly different way, 'Ad recipient' option is available whether we are in expert mode or not and it work ok. And instead of a text button, we use an icon.
![image](https://user-images.githubusercontent.com/57331244/169968502-37b1296c-5928-4084-95ae-b74e76ff6b2b.png)

Should we close this issue?
