### ISSUE TITLE
Add bg image for liquidity page

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#892]

**Comment by MilanVojnovic95** [comment]
This issue is connected to #1004[](https://github.com/levelkdev/swapr-dapp/pull/1004) which is in review state so this issue should not be in backlog anymore.

**Comment by Diogomartf** [comment]
Yes. Thanks 🙌

On May 30, 2022, "linear-app[bot]" ***@***.***> wrote:
> This issue is connected to #1004 <https://github.com/levelkdev/swapr-
> dapp/pull/1004> which is in review state so this issue should not be
> in backlog anymore.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/levelkdev/swapr-dapp/issues/892#issuecomment-
1140965792>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABLG5MRXHE276KK3432FYETVMSHYLANCNFSM5TNDQYSA>.
You are receiving this because you were assigned.Message ID:
***@***.***>
